android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
kotlin.experimental.tryK2=true
android.autoDownloadSdk=true
